version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: mariadb_backend_simr #Ganti nama bro sesuai selera
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: simr
      MARIADB_USER: bayu #Ganti nama bro sesuai selera
      MARIADB_PASSWORD: bayu #Ganti password bro sesuai selera
    ports:
      - "3310:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
