version: '3.8'

services:
  simr-nest:
    image: node:20-alpine
    container_name: simr-nest
    working_dir: /app
    restart: on-failure
    volumes:
      - .:/app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
    command: >
      sh -c "npm install; npx prisma generate; npx prisma db push; npm run start"
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: mariadb_backend_simr
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "${MARIADB_PORT}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
